### ISSUE TITLE
Error resolving template

### ISSUE THREAD

**Issue by masterxq** [urlaubsverwaltung/zeiterfassung#236]
Hallo,

erstmal vielen Dank für deine Arbeit! Ich finde die Urlaubsverwaltung wirklich super und sehe mit Spannung einer Fertigen Zeitverwaltung entgegen.

Wirklich super gemacht!

Ohne mit großer Sicherheit sagen zu können das es nicht an einem Konfigurationsproblem liegt habe ich ein Problem mit der dem jar release 1.4 und ebenfalls mit selbstgebauten Jars vom aktuellen Main.

Es funktioniert einwandfrei, wenn ich die Applikation direkt starte!

Es gelingt dem System nicht einige Templates zu resolven. Hier ein Beispielhafter log Eintrag, in dem Fall vom main von gestern, sehr ähnlich sieht es auch beim JAR-release 1.4 aus:

```
2023-04-13T07:17:19.760+02:00 ERROR 2139105 --- [nio-8095-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.thymeleaf.exceptions.
TemplateInputException: Error resolving template [/usermanagement/user/working-time-settings], template might not exist or might not be accessible by any of the configured Template Resolvers (template: "usermanagement/users" - line 282, col 27)] with r
oot cause

org.thymeleaf.exceptions.TemplateInputException: Error resolving template [/usermanagement/user/working-time-settings], template might not exist or might not be accessible by any of the configured Template Resolvers (template: "usermanagement/users" - 
line 282, col 27)
        at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869) ~[thymeleaf-3.1.1.RELEASE.jar!/:3.1.1.RELEASE]
        at org.thymeleaf.engine.TemplateManager.parseStandalone(TemplateManager.java:250) ~[thymeleaf-3.1.1.RELEASE.jar!/:3.1.1.RELEASE]
        at org.thymeleaf.standard.expression.FragmentExpression.resolveExecutedFragmentExpression(FragmentExpression.java:567) ~[thymeleaf-3.1.1.RELEASE.jar!/:3.1.1.RELEASE]
        at org.thymeleaf.standard.processor.AbstractStandardFragmentInsertionTagProcessor.computeFragment(AbstractStandardFragmentInsertionTagProcessor.java:419) ~[thymeleaf-3.1.1.RELEASE.jar!/:3.1.1.RELEASE]
        at org.thymeleaf.standard.processor.AbstractStandardFragmentInsertionTagProcessor.doProcess(AbstractStandardFragmentInsertionTagProcessor.java:115) ~[thymeleaf-3.1.1.RELEASE.jar!/:3.1.1.RELEASE]
        at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74) ~[thymeleaf-3.1.1.RELEASE.jar!/:3.1.1.RELEASE]
        at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95) ~[thymeleaf-3.1.1.RELEASE.jar!/:3.1.1.RELEASE]
        at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633) ~[thymeleaf-3.1.1.RELEASE.jar!/:3.1.1.RELEASE]
        at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314) ~[thymeleaf-3.1.1.RELEASE.jar!/:3.1.1.RELEASE]
        at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.1.RELEASE.jar!/:3.1.1.RELEASE]
        at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136) ~[thymeleaf-3.1.1.RELEASE.jar!/:3.1.1.RELEASE]
        at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:592) ~[thymeleaf-3.1.1.RELEASE.jar!/:3.1.1.RELEASE]
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.1.RELEASE.jar!/:3.1.1.RELEASE]
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077) ~[thymeleaf-3.1.1.RELEASE.jar!/:3.1.1.RELEASE]
        at org.thymeleaf.spring6.view.ThymeleafView.renderFragment(ThymeleafView.java:372) ~[thymeleaf-spring6-3.1.1.RELEASE.jar!/:3.1.1.RELEASE]
....
```

Die Seite kann grundlegend noch aufgerufen werden, aber Beispielsweise kann ich keine Personen mehr editieren und keine Zeiteinträge mehr verfassen.

Der Server läuft mit Debian stable.

```
> dpkg -l|grep openjdk
ii  openjdk-17-jdk:amd64                      17.0.4+8-1~deb11u1                  amd64        OpenJDK Development Kit (JDK)
ii  openjdk-17-jdk-headless:amd64             17.0.4+8-1~deb11u1                  amd64        OpenJDK Development Kit (JDK) (headless)
ii  openjdk-17-jre:amd64                      17.0.4+8-1~deb11u1                  amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-17-jre-headless:amd64             17.0.4+8-1~deb11u1                  amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
```

Ich hoffe, du/ihr könnt hiermit etwas anfangen, falls weiter Fragen auftreten probiere ich gerne zu helfen.

Beste Grüße

Edit:
Ich bin ehrlich gesagt gar nicht ganz sicher, ob ich die JAR richtig baue. Das Betrifft natürlich nur die selbstgebaute JAR. Ich nutze folgenden Befehl:
`./mvnw package`

**Comment by derTobsch** [comment]
Guten Morgen @masterxq,

ich bin leider gerade erst auf dieses Ticket aufmerksam geworden. Gibt es das Problem immer noch? Wie sieht deine Konfiguration aus? Wie startest du die Anwendung?

**Comment by masterxq** [comment]
Das weiß ich leider inzwischen nicht mehr genau,
aber ich denke, es war einfach:
`java -jar ...`

Ich werde es bei Gelegenheit wieder probieren. Ich rechne aber zu 99 % damit das dein Fix es auch für mich lösen wird.

Wenn es noch Probleme gibt, werde ich ein neues Issue erstellen.

Vielen Dank

**Comment by masterxq** [comment]
@derTobsch 
Ok, ja command war richtig (java -jar), fix hat nicht für die jar funktioniert, war glaube ich nur die eine hälfte. Funktioniert nur wenn man irgendwie im filesystem arbeitet da repariert sich der path. Habs es für mich gepatched und die jar neu gebaut:
```bash
# Patch: ~{/xxx -> ~{xxx
find BOOT-INF/classes/templates -name "*.html" -print0 \
  | xargs -0 sed -i 's/~{\//~{/g'
```
Seitdem bisher keine Probleme ^^ Aber du solltest dir das wahrscheinlich trotzdem genauer anschauen, aber ich wäre dankbar wenn du da noch einen fix bringen würdest, das ewige patchen ist doch irgendwie nicht so praktisch...
Ich frage mich gleichzeitig ob ich der einzige bin der die jar nutzt ^^ Der Fehler macht zwar nicht das gar nichts mehr geht, aber so toll ist das schon nicht...
Kann halt sein das viele die die jar probieren denken das es viel schlechter ist als es ist weil sie den log übersehen oder ignorieren...
